# Generated by Django 4.2.5 on 2023-09-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(default='CD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(default='CD', max_length=10),
            preserve_default=False,
        ),
    ]
